name: Bug汇报(表单版)
description: 反馈本插件的Bug或问题
title: "Bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查项目
      description: 在汇报之前，你需要确认
      options:
        - label: 你使用的是由ybw0014提供的汉化版本(版本号中含有ybw0014)
          required: true
        - label: 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
          required: true
        - label: 你已经检验过下载的文件的sha值，确认已完整下载文件 (暂未推出)
          required: false
        - label: 你没有对下载的文件内容进行任何更改
          required: true
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 详细描述你要汇报的问题，越详细越好
      placeholder: 只说"不能用"没法让开发者定位问题。
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤
      description: 请详细描述如何才能复现该问题。如果有视频，请在此提供视频链接。
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: |
        你觉得应该发生什么。
        有时候，问题的原因是你误解了某个功能。
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: 服务器日志 / 错误报告
      description: |
        请查看服务器日志中是否包含任何报错，如果有请上传至 [https://paste.guizhanss.net/](https://paste.guizhanss.net/) 并在此填入链接。
        如果`/plugins/Slimefun/error-reports`文件夹中含有错误报告，也请上传并提供链接。
    validations:
      required: false
  - type: input
    id: version-server
    attributes:
      label: 服务端版本
      description: 请填写服务端软件与版本 (例如 paper-1.18-6)
    validations:
      required: true
  - type: input
    id: version-slimefun
    attributes:
      label: Slimefun版本
      description: 请填写Slimefun版本 (例如 v4.9-canary-08120db)
    validations:
      required: true
  - type: input
    id: version-plugin
    attributes:
      label: SlimeTinker版本
      description: 请填写SlimeTinker版本，只需填写Build后面的数字版本即可 (`Build 7 zh-CN(ybw0014) (git 9ef7fee)`只需填写`7`即可)
    validations:
      required: true
