name: Sync To Gitee

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SYNC_SECRET }}
        with:
          source-repo: "git@github.com:ybw0014/SlimeTinker-CN.git"
          destination-repo: "git@gitee.com:ybw0014/SlimeTinker-CN.git"
